var color = [
  "white",
  "black",
  "yellow",
  "red",
  "blue",
  "brown",
  "green",
  "purple",
  "orange",
  "silver",
  "scarlet",
  "rainbow",
  "indigo",
  "ivory",
  "navy",
  "olive",
  "teal",
  "pink",
  "magenta",
  "maroon",
  "sienna",
  "gold",
  "golden"
];
var adjective = [
  "abandoned",
  "aberrant",
  "accidentally",
  "aggressive",
  "aimless",
  "alien",
  "angry",
  "appropriate",
  "barbaric",
  "beacon",
  "big",
  "bitter",
  "bleeding",
  "brave",
  "brutal",
  "cheerful",
  "dancing",
  "dangerous",
  "dead",
  "deserted",
  "digital",
  "dirty",
  "disappointed",
  "discarded",
  "dreaded",
  "eastern",
  "eastern",
  "elastic",
  "empty",
  "endless",
  "essential",
  "eternal",
  "everyday",
  "fierce",
  "flaming",
  "flying",
  "forgotten",
  "forsaken",
  "freaky",
  "frozen",
  "full",
  "furious",
  "ghastly",
  "global",
  "gloomy",
  "grim",
  "gruesome",
  "gutsy",
  "helpless",
  "hidden",
  "hideous",
  "homeless",
  "hungry",
  "insane",
  "intense",
  "intensive",
  "itchy",
  "liquid",
  "lone",
  "lost",
  "meaningful",
  "modern",
  "monday's",
  "morbid",
  "moving",
  "needless",
  "nervous",
  "new",
  "next",
  "ninth",
  "nocturnal",
  "northernmost",
  "official",
  "old",
  "permanent",
  "persistent",
  "pointless",
  "pure",
  "quality",
  "random",
  "rare",
  "raw",
  "reborn",
  "remote",
  "restless",
  "rich",
  "risky",
  "rocky",
  "rough",
  "running",
  "rusty",
  "sad",
  "saturday's",
  "screaming",
  "serious",
  "severe",
  "silly",
  "skilled",
  "sleepy",
  "sliding",
  "small",
  "solid",
  "steamy",
  "stony",
  "stormy",
  "straw",
  "strawberry",
  "streaming",
  "strong",
  "subtle",
  "supersonic",
  "surreal",
  "tainted",
  "temporary",
  "third",
  "tidy",
  "timely",
  "unique",
  "vital",
  "western",
  "wild",
  "wooden",
  "worthy",
  "bitter",
  "boiling",
  "brave",
  "cloudy",
  "cold",
  "confidential",
  "dreadful",
  "dusty",
  "eager",
  "early",
  "grotesque ",
  "harsh",
  "heavy",
  "hollow",
  "hot",
  "husky",
  "icy",
  "late",
  "lonesome",
  "long",
  "lucky",
  "massive",
  "maximum",
  "minimum",
  "mysterious",
  "outstanding",
  "rapid",
  "rebel",
  "scattered",
  "shiny",
  "solid",
  "square",
  "steady",
  "steep",
  "sticky",
  "stormy",
  "strong",
  "sunday's",
  "swift",
  "tasty"
];
var science = [
  "alarm",
  "albatross",
  "anaconda",
  "antique",
  "artificial",
  "autopsy",
  "autumn",
  "avenue",
  "backpack",
  "balcony",
  "barbershop",
  "boomerang",
  "bulldozer",
  "butter",
  "canal",
  "cloud",
  "clown",
  "coffin",
  "comic",
  "compass",
  "cosmic",
  "crayon",
  "creek",
  "crossbow",
  "dagger",
  "dinosaur",
  "dog",
  "donut",
  "door",
  "doorstop",
  "electrical",
  "electron",
  "eyelid",
  "firecracker",
  "fish",
  "flag",
  "flannel",
  "flea",
  "frostbite",
  "gravel",
  "haystack",
  "helium",
  "kangaroo",
  "lantern",
  "leather",
  "limousine",
  "lobster",
  "locomotive",
  "logbook",
  "longitude",
  "metaphor",
  "microphone",
  "monkey",
  "moose",
  "morning",
  "mountain",
  "mustard",
  "neutron",
  "nitrogen",
  "notorious",
  "obscure",
  "ostrich",
  "oyster",
  "parachute",
  "peasant",
  "pineapple",
  "plastic",
  "postal",
  "pottery",
  "proton",
  "puppet",
  "railroad",
  "rhinestone",
  "roadrunner",
  "rubber",
  "scarecrow",
  "scoreboard",
  "scorpion",
  "shower",
  "skunk",
  "sound",
  "street",
  "subdivision",
  "summer",
  "sunshine",
  "tea",
  "temple",
  "test",
  "tire",
  "tombstone",
  "toothbrush",
  "torpedo",
  "toupee",
  "trendy",
  "trombone",
  "tuba",
  "tuna",
  "tungsten",
  "vegetable",
  "venom",
  "vulture",
  "waffle",
  "warehouse",
  "waterbird",
  "weather",
  "weeknight",
  "windshield",
  "winter",
  "wrench",
  "xylophone",
  "alpha",
  "arm",
  "beam",
  "beta",
  "bird",
  "breeze",
  "burst",
  "cat",
  "cobra",
  "crystal",
  "drill",
  "eagle",
  "emerald",
  "epsilon",
  "finger",
  "fist",
  "foot",
  "fox",
  "galaxy",
  "gamma",
  "hammer",
  "heart",
  "hook",
  "hurricane",
  "iron",
  "jazz",
  "jupiter",
  "knife",
  "lama",
  "laser",
  "lion",
  "mars",
  "mercury",
  "moon",
  "moose",
  "neptune",
  "omega",
  "panther",
  "planet",
  "pluto",
  "plutonium",
  "poseidon",
  "python",
  "ray",
  "sapphire",
  "scissors",
  "screwdriver",
  "serpent",
  "sledgehammer",
  "smoke",
  "snake",
  "space",
  "spider",
  "star",
  "steel",
  "storm",
  "sun",
  "swallow",
  "tiger",
  "uranium",
  "venus",
  "viper",
  "wrench",
  "yard",
  "zebra"
];

export function projectname() {
  var name = "";
  var prefix = color.concat(adjective);
  var suffix = science;
  var n1 = parseInt(Math.random() * prefix.length);
  var n1ex = parseInt(Math.random() * prefix.length);
  if (n1ex == n1) {
    n1ex = n1 + 1;
  }
  var n2 = parseInt(Math.random() * suffix.length);
  var prename = prefix[n1].slice(0, 1).toUpperCase() + prefix[n1].slice(1);
  var prenameex =
    prefix[n1ex].slice(0, 1).toUpperCase() + prefix[n1ex].slice(1);
  var sufname = suffix[n2].slice(0, 1).toUpperCase() + suffix[n2].slice(1);
  var n3 = parseInt(Math.random() * 85 + 15);
  if (n3 <= 15) {
    name = prenameex + " " + prename + " " + sufname;
  } else if (n3 > 15 && n3 <= 30) {
    name = sufname + " " + prename;
  } else {
    name = prename + " " + sufname;
  }
  if (document.getElementById("codename")) {
    var elem = document.getElementById("codename");
    var parentElem = document.getElementById("result");
    parentElem.removeChild(elem);
  }

  return name;
}

export function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max));
}

export function battle(a, d) {
  var EVA_FACTOR = 1.125;
  var EVA_INHERENT = 0.5;
  var l = [];

  a.hp = 10;
  d.hp = 10;

  // attack: attack,
  // defense: speed,
  // speed: defense,

  a = clone(a);
  d = clone(d);

  while (d.hp > 0) {
    a = [d, (d = a)][0];
    let r = d.speed - a.hit;
    let dg = 0;
    if (
      !(
        Math.random() <
        EVA_INHERENT +
          ((r > 0 ? 1 : -1) * Math.pow(Math.abs(r), EVA_FACTOR)) / 100
      )
    ) {
      dg = a.attack - d.defense < 1 ? 1 : a.attack - d.defense;
      d.hp = d.hp < dg ? 0 : d.hp - dg;
    }
    l.push({ attacker: a.name, damage: dg });
    console.log({ attacker: a.name, damage: dg });
  }

  function clone(c) {
    return JSON.parse(JSON.stringify(c));
  }

  return { winner: a, log: l };
}

// var p1 = {id:'player 1',hp:10,atk:3,def:1,hit:1,eva:1};
// var p2 = {id:'player 2',hp:10,atk:1,def:3,hit:1,eva:3};
